info:
  profile: default
  from: git
server:
  port: 8060
spring:
  cloud:
    config:
      server:
        git:
          uri: http://git.wisdontech.com/wisdontech/project/config/config-center.git
          searchPaths: config-repo, config-repo/config-server
          username: deploy
          password: deploy.1234  
logging:
  path: /opt/spring-boot-project/log/${spring.application.name}-${server.port}
  level:
    root: INFO
    org:
      springframework: INFO