server:
  port: 9020
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/
logging:
  path: /opt/spring-boot-project/log/${spring.application.name}-${server.port}
  level:
    root: INFO
    org:
      springframework: INFO