spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qianhongtang/spring-cloud-demo.git
          searchPaths: config-center/{application}
          #username: username
          #password: password
logging:
  path: /opt/spring-boot-project/log/${spring.application.name}-${server.port}
  level:
    root: INFO
    org:
      springframework: INFO