server:
  port: 9000
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
management:
  endpoint:
    shutdown:
      enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
logging:
  path: /opt/spring-boot-project/log/${spring.application.name}-${server.port}
  level:
    root: INFO
    org:
      springframework: INFO