spring:
  application:
    name: consul-gateway-zuul-server
  profiles:
    active: dev
zuul:
  routes:
    consul-service:
      path: /consul-service/**
      serviceId:  consul-service
    consul-service-consumer-feign:
      path: /consul-service-consumer-feign/**
      serviceId:  consul-service-consumer-feign
    consul-service-consumer-feign-ribbon-hystrix:
      path: /consul-service-consumer-feign-ribbon-hystrix/**
      serviceId:  consul-service-consumer-feign-ribbon-hystrix
