spring:
  application:
    name: consul-gateway-zuul-oauth2-server
  profiles:
    active: dev
zuul:
  routes:
    consul-service:
      path: /consul-service/**
      serviceId:  consul-service
    consul-service-consumer-feign:
      path: /consul-service-consumer-feign/**
      serviceId:  consul-service-consumer-feign