server:
  port: 9000
eureka:
  instance:
    hostname: peer0
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
logging:
  path: /opt/spring-boot-project/log/${spring.application.name}-${server.port}
  level:
    root: INFO
    org:
      springframework: INFO