server:
  port: 8501
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
logging:
  path: /opt/spring-boot-project/log/${spring.application.name}-${server.port}
  level:
    root: INFO
    org:
      springframework: INFO