spring:
  cloud:
    config:
      server:
        git:
          uri: http://git.wisdontech.com/wisdontech/project/public/spring-cloud-demo.git
          searchPaths: config-center/{application}
          username: deploy
          password: deploy.1234  
logging:
  path: /opt/spring-boot-project/log/${spring.application.name}-${server.port}
  level:
    root: INFO
    org:
      springframework: INFO